version: '3.3'

services:
  qlee_db:
    image: postgres:16-alpine
    container_name: qlee_db_postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment: 
      - POSTGRES_PASSWORD=change_me
      - POSTGRES_USER=qlee_blog_app
      - POSTGRES_DB=qlee_blog_app_db